import os
import warnings
from typing import Optional

import lm_eval
import torch
import transformers
from cfg import CFGLogitsProcessor, classifier_free_guidance
from lm_eval.api.instance import Instance
from lm_eval.api.model import LM
from tqdm.auto import tqdm
from transformers import LogitsProcessorList


def get_model_max_length(model):
    # https://stackoverflow.com/a/78737021/9889508
    typical_fields = [
        "max_position_embeddings",
        "n_positions",
        "seq_len",
        "seq_length",
        "n_ctx",
        "sliding_window",
    ]
    context_windows = [
        getattr(model.config, field) for field in typical_fields if field in dir(model.config)
    ]
    return min(context_windows) if context_windows else 1024


class CFGLM(LM):
    """
    Wrapper for evaluating a model with classifier free guidance (CFG)
    via the Eleuther eval harness.

    Only supports tasks that require `generate_until` or `loglikelihood` methods.
    `loglikelihood_rolling` is not supported.

    We do not need `loglikelihood_rolling` anyway because we will not evaluate on tasks
    that require it.

    Args:
        model_name (str): The name of the model to be evaluated, to be passed to
            transformers.from_pretrained(model_name) to load the model.
        guidance_scale (float): The guidance scale to be used in classifier free
            guidance.
        uncond_prompt (str): The unconditioned prompt or negative prompt to be used in
            classifier free guidance. Can be omitted.
    """

    def __init__(
        self,
        model_name: str,
        guidance_scale: float,
        uncond_prompt: Optional[str] = None,
        *args,
        **kwargs,
    ) -> None:
        super().__init__(*args, **kwargs)
        self.model = transformers.AutoModelForCausalLM.from_pretrained(model_name)
        self.tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)
        self.default_max_new_tokens = 256  # match the default of HFLM

        self.model_max_length = get_model_max_length(self.model)

        # Removes  "Setting `pad_token_id` to `eos_token_id`:None for open-end generation." warning
        self.model.generation_config.pad_token_id = self.tokenizer.eos_token_id

        self.guidance_scale = guidance_scale

        self.device = (
            "cuda"
            if torch.cuda.is_available()
            else "mps" if torch.backends.mps.is_available() else "cpu"
        )

        self.model.to(self.device)

        self.uncond_ids: Optional[torch.LongTensor] = None
        if uncond_prompt is not None:
            self.uncond_ids = self.tokenizer(uncond_prompt, return_tensors="pt")["input_ids"]
            self.uncond_ids = self.uncond_ids.to(self.device)

    def loglikelihood_rolling(self, requests) -> list[float]:
        print("loglikelihood_rolling is not supported")
        return [0]

    def loglikelihood(self, requests: list[Instance]) -> list[tuple[float, bool]]:
        """
        - Each request contains Instance.args : Tuple[str, str] containing 1. an input
          string to the LM and 2. a target string on which the loglikelihood of the LM
          producing this target, conditioned on the input, will be returned.
        - Each request will have, as result, (ll, is_greedy): Tuple[float, int]
          returned, where ll is a floating point number representing the log probability
          of generating the target string conditioned on the input, and is_greedy being
          either the value 0 or 1, with it being 1 if and only if the target string
          would be generated by greedy sampling from the LM (that is, if the target
          string is the most likely N-token string to be output by the LM given the
          input.)
        """
        os.environ["TOKENIZERS_PARALLELISM"] = "false"
        results: list[tuple[float, bool]] = []

        for instance in tqdm(requests):
            input_str, target_str = instance.args

            input_tokens = self.tokenizer(
                input_str,
                return_tensors="pt",
                max_length=self.model_max_length,
                truncation=True,
                truncation_strategy="only_first",
            )["input_ids"]
            target_tokens = self.tokenizer(
                target_str,
                max_length=self.model_max_length,
                truncation=True,
                truncation_strategy="only_last",
            )["input_ids"]

            # (B, S)
            context = input_tokens.clone()

            total_loglikelihood = 0.0
            is_greedy = True

            cond_past_key_values = None
            uncond_past_key_values = None
            for token_id in target_tokens:
                context = context.to(self.device)
                log_probs, cond_past_key_values, uncond_past_key_values = classifier_free_guidance(
                    self.model,
                    self.guidance_scale,
                    context,
                    self.uncond_ids,
                    use_cache=True,
                    cond_past_key_values=cond_past_key_values,
                    uncond_past_key_values=uncond_past_key_values,
                )

                total_loglikelihood += log_probs[:, token_id].item()

                greedy_token_id = torch.argmax(log_probs).item()

                # if even just 1 token isn't greedy , then the whole gen isn't greedy
                if token_id != greedy_token_id:
                    is_greedy = False

                # since we're using cache, we can feed in just the new token as
                # the context for the next iteration
                # (B, 1)
                context = torch.tensor([[token_id]], device=self.device, dtype=torch.long)

            results.append((total_loglikelihood, is_greedy))

        return results

    def generate_until(self, requests: list[Instance]) -> list[str]:
        """
        - Each request contains Instance.args : Tuple[str, dict] containing 1. an input
          string to the LM and 2. a dictionary of keyword arguments used to control
          generation parameters.
        - Using this input and these generation parameters, text will be sampled from
          the language model (typically until a maximum output length or specific
          stopping string sequences--for example, {"until": ["\n\n", "."],
          "max_gen_toks": 128}).
        - The generated input+output text from the model will then be returned.
        """
        os.environ["TOKENIZERS_PARALLELISM"] = "false"
        warnings.filterwarnings("ignore", category=UserWarning, module="transformers")

        results: list[str] = []

        for instance in tqdm(requests):
            input_str, kwargs = instance.args

            max_new_tokens = (
                kwargs.pop("max_gen_toks", self.default_max_new_tokens)
                or self.default_max_new_tokens
            )
            stop_strings = kwargs.pop("until", None)
            generate_kwargs = {
                **kwargs,
                "max_new_tokens": max_new_tokens,
                "stop_strings": stop_strings,
                "tokenizer": self.tokenizer,  # need to pass tokenizer for stop_strings
            }

            input_token_ids = self.tokenizer(
                input_str,
                return_tensors="pt",
                truncation=True,
                max_length=self.model_max_length,
                truncation_strategy="only_first",
            ).to(self.device)

            # (1, S)
            outputs = self.model.generate(
                **input_token_ids,
                **generate_kwargs,
                logits_processor=LogitsProcessorList(
                    [
                        CFGLogitsProcessor(
                            self.model,
                            self.guidance_scale,
                            self.uncond_ids,
                            use_cache=True,
                        )
                    ]
                ),
                use_cache=True,
            )

            output_str = self.tokenizer.decode(outputs[0, :])

            # output_str includes the input_str, so no need to do input_str + output_str
            results.append(output_str)

        return results


def evaluate(
    models_list: list, task_list: list, guidance_scales: list, task_to_metric: dict
) -> dict:
    task_results = {task: [] for task in task_list}

    for guidance_scale in guidance_scales:
        for model_name in models_list:
            print(f"EVALUATING MODEL:{model_name} WITH GUIDANCE SCALE:{guidance_scale}")
            lm_to_eval = CFGLM(model_name=model_name, guidance_scale=guidance_scale)
            results = lm_eval.simple_evaluate(lm_to_eval, tasks=task_list, cache_requests=True)[
                "results"
            ]

            for task, metrics in results.items():
                metric = task_to_metric[task]

                metric_key = next((key for key in metrics if key.startswith(f"{metric},")), None)

                score = metrics.get(metric_key, None) if metric_key else None
                task_results[task].append(
                    {
                        "Model": model_name,
                        "Guidance Scale": guidance_scale,
                        "Score": score,
                    }
                )
    return task_results
